import { Lead, SmartList } from "@/lib/lc-types";

export const leads: Lead[] = [
  { id: "L-001",
    firstName: "Lead",
    lastName: "L-001",
    email: "lead-l-001@example.com",
    company: "Company L-001",
    attachmentLink: "",
    source: "aoncybersecurity",
    owner: "Internal",
  },
  { id: "L-002",
    firstName: "Lead",
    lastName: "L-002",
    email: "lead-l-002@example.com",
    company: "Company L-002",
    attachmentLink: "",
    source: "aoncybersecurity",
    owner: "Internal",
  },
  { id: "L-003",
    firstName: "Lead",
    lastName: "L-003",
    email: "lead-l-003@example.com",
    company: "Company L-003",
    attachmentLink: "",
    source: "aoncybersecurity",
    owner: "Internal",
  },
  { id: "L-004",
    firstName: "Lead",
    lastName: "L-004",
    email: "lead-l-004@example.com",
    company: "Company L-004",
    attachmentLink: "",
    source: "viviumforms",
    owner: "Internal",
  },
  { id: "L-005",
    firstName: "Lead",
    lastName: "L-005",
    email: "lead-l-005@example.com",
    company: "Company L-005",
    attachmentLink: "",
    source: "viviumforms",
    owner: "Internal",
  },
];

export const leadSmartLists: SmartList[] = [
  { id: "ls-1", name: "AON Cybersecurity Leads", type: "Dynamic", count: 3, entityType: "lead" },
  { id: "ls-2", name: "Vivium Form Leads", type: "Dynamic", count: 2, entityType: "lead" },
  { id: "ls-3", name: "All Leads", type: "Static", count: 5, entityType: "lead" },
];
